[versions]
agp = "8.13.2"
kotlin = "2.3.0"
junit = "4.13.2"
androidx-test-runner = "1.7.0"
espressoCoreVersion = "3.7.0"
coreKtx = "1.17.0"

[libraries]
# Core AndroidX (শুধু essential)
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

# Testing only
junit = { group = "junit", name = "junit", version.ref = "junit" }
runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test-runner" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCoreVersion" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
